name: XYZPodcast
targets:
  XYZPodcast:
    type: application
    platform: iOS
    deploymentTarget: '15.0'
    sources:
      - path: .
        includes:
          - "ViewController.swift"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xyzpodcast.app
        INFOPLIST_FILE: Info.plist
        CODE_SIGNING_ALLOWED: NO
        TARGETED_DEVICE_FAMILY: "1,2"
